### ISSUE TITLE
1.9 support?

### ISSUE THREAD

**Issue by open-trade** [cmeng-git/vpx-android#2]
谢谢你的工作，能不能麻烦加上1.9，兄弟也在新加坡，请你喝酒，：）

**Comment by cmeng-git** [comment]
Released v1.1.6 with scripts change to support libvpx v1.10.0 build.

**Comment by rustdesk** [comment]
@cmeng-git 不知道你对https://github.com/rustdesk/rustdesk 这个项目是否感兴趣? 近期受到一些国内科技媒体的报道，也接到一些国内外投资机构的咨询，目前在积极洽谈中。很希望找到更强的技术合伙人，如果有兴趣，可以发邮件给我，网站里有邮箱。谢谢

**Comment by cmeng-git** [comment]
Thanks for the invitation; however I do not have the extra resource as I am handling multiple projects currently.

By the way if you are using vp9 ecoder in libvpx 1.10.0, you need to apply the following patches.

[vpx_encode_h.zip](https://github.com/cmeng-git/vpx-android/files/6760884/vpx_encode_h.zip)

**Comment by rustdesk** [comment]
谢谢

**Comment by cmeng-git** [comment]
Please refer to https://github.com/cmeng-git/atalk-android/tree/master/aTalk/jni for the latest updated scripts and build instructions. This repository is not further maintained since v1.1.7.
