### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sany1231** [cmeng-git/vpx-android#3]
Hello, i am trying to build vpx for armv7 arch but no luck :(

/build-vpx4android.sh _**arm64-v8a**_ works fine but when i try to run  ./build-vpx4android.sh _**armeabi-v7a**_ then error occurs 
```
/home/ubuntu/vpx-android/android-toolchain/bin/arm-linux-androideabi-ld: unrecognised emulation mode: arch=armv7-a
Supported emulations: armelf_linux_eabi armelfb_linux_eabi
```

compiling on: 32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)
libvpx 1.10.0

where is the problem?

**Comment by cmeng-git** [comment]
Please refer to https://github.com/cmeng-git/atalk-android/tree/master/aTalk/jni for the latest updated scripts and build instructions. This repository is not further maintained since v1.1.7.
